service: ps5-stock-checker
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource: !Ref PS5StockTopic

functions:
  check:
    handler: src/stock.check
    memorySize: 1600
    timeout: 30
    environment:
      topic: !Ref xboxStockTopic
      checkUrl: https://www.amazon.in/stores/page/1D2AEE2B-0C0B-4B95-902E-247C55AE2073?ingress=2&visitId=14e14595-5368-4acd-9e08-17ab40bf0f20&ref_=ast_bln
      sku: 6426149
    events:
      - schedule: rate(5 minutes)

resources:
  Resources:
    PS5StockTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: xbox Stock Topic
        TopicName: xbox_Stock_Topic
    PS5StockTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref xboxStockTopic
        Protocol: sms
        Endpoint: 7003067988
