service: xbox-stock-checker
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource: !Ref xboxStockTopic

functions:
  check:
    handler: src/stock.check
    memorySize: 1600
    timeout: 30
    environment:
      topic: !Ref xboxStockTopic
      checkUrl: https://www.flipkart.com/microsoft-xbox-series-x-1024-gb/p/itm63ff9bd504f27?pid=GMCFVPFCFDFGJHGG&otracker=wishlist&lid=LSTGMCFVPFCFDFGJHGGLGCF4A&fm=organic&iid=cea9478e-efab-495d-8ce8-5611b4709f15.GMCFVPFCFDFGJHGG.PRODUCTSUMMARY&ppt=pp&ppn=pp&ssid=kqipqsfcy80000001628998420256
      sku: MICROSOFT Xbox Series X 1024 GB  (Black)
    events:
      - schedule: rate(5 minutes)

resources:
  Resources:
    PS5StockTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: xbox Stock Topic
        TopicName: xbox_Stock_Topic
    PS5StockTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref xboxStockTopic
        Protocol: sms
        Endpoint: 7003067988
